### ISSUE TITLE
Original documentation site is down

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa-community.github.io#5]
I know this is not the right place to post this request but I have not found a better way to let you know. Sorry.

Default scenarios definitions are pointing to a web site (for example http://www.sympa.org/distribution/current/default/scenari/send.closed) that has been down for quite a long time (The server is currently unavailable for maintenance). That information has not been ported to the git site. Is there an alternative site to get that information?

**Comment by ikedas** [comment]
Hi @qosobrin,
I don't understand what is "pointing to a web site". Could you please show us the URL of description you saw?

In new documentation, authorisation scenario is described in "Customizing Sympa" - "[Authorization scenarios](https://github.com/sympa-community/sympa-community.github.io/blob/master/manual/customize/basics-scenarios.md)".

**Comment by qosobrin** [comment]
Sorry for not pointing that out. For example, in https://www.sympa.org/manual_6.1/parameters-privileges#subscribe every parameter has an explanation, but the site those explanations are pointing (for example http://www.sympa.org/distribution/current/default/scenari/send.closed) are broken or the site is down.

Do you follow me? Thank you very much. Regards.

**Comment by ikedas** [comment]
I got it: http://www.sympa.org/distribution/current/ does no longer exist. I'll ask the person in charge.

However, please see the new documentation, unless you are using very old version: Documentation on https://www.sympa.org/ contains several outdated things and will not be updated anymore.

By the same reason, please refer to the scenario files included in your installation, instead of files on the web. The location of default scenario files is [$DEFAULTDIR](https://github.com/sympa-community/sympa-community.github.io/blob/master/manual/layout.md#defaultdir)/scenari, as described in the new documentation above.

**Comment by qosobrin** [comment]
OK, thanks. Documentation on the old site (https://www.sympa.org/ ) is still more complete than the new one.  This transition to a new site is somewhat confusing, but we have to get used to it.

Thank you very much. Best regards.

**Comment by ikedas** [comment]
Newer documentation did not import entire content of older.  Because we couldn't contact with some authors of older one so that we could get permission to re-publish their works under new license (CC BY-SA).  If you feel new documentation lacking something, please consider contributing the work by your own.

Thanks for information. This ticket may be closed in a few days.

Regards,

**Comment by racke** [comment]
Or report an issue pointing out what is missing on the new site.

**Comment by ikedas** [comment]
> Or report an issue pointing out what is missing on the new site.

Oh yes, such suggestion also helps much.

**Comment by qosobrin** [comment]
Sure. I'll try one way (contributing) or the other (reporting issues) depending on the case. I will open new issues according to my necessities, so I'll close this one myself. Thank you very much in advance. 

Regards.

**Comment by dverdin** [comment]
Hi, I fixed the liks on the previous Sympa web site.

**Comment by ikedas** [comment]
Thanks @dverdin.

FYI: These lists of scenarios are automatically generated from source distribution, when the documentation was provided as LaTex source (before it had been moved to dokuwiki).

I personally think, if there are no strong suggestion for such automatic content, it would not be imported to new documentation. Because these things may make maintenance work complicated.
