### ISSUE TITLE
sympa_transport file defined in postfix configuration page but not used

### ISSUE THREAD

**Issue by qosobrin** [sympa-community/sympa-community.github.io#92]
In https://github.com/sympa-community/sympa-community.github.io/blob/master/manual/install/configure-mail-server-postfix.md -> _Virtual domain setting_ -> _Initial setting_ the documentation guides users to create the file `$SYSCONFDIR/sympa_transport`, change its access permissions and owner but the file never seems to be used later in the documentation. Meanwhile, the same page also guides users to create a file with a similar name `$SYSCONFDIR/transport.sympa` that is used along the documentation.

I wonder if references to `$SYSCONFDIR/sympa_transport` are an error and are supposed to be changed to `$SYSCONFDIR/transport.sympa` or are OK and should be left as they are.

Thank you very much in advance.
Best regards.

**Comment by ikedas** [comment]
Please see full section of "[Virtual domain setting](https://sympa-community.github.io/manual/install/configure-mail-server-postfix.html#virtual-domain-setting)".
 
  - `transport.sympa` and `virtual.sympa` are used to define the addresses not managed by Sympa, i.e. the required addresses regardless of whether the lists are created or closed.
  - `sympa_transport` includes definitions the addresses managed exclusively by Sympa, i.e. the addresses added or deleted as the lists are created or closed.  That's why it is initially empty.

For example, if you have to add an address with the same domain as the mailing list service but it should be execluded from the service, such address may be added as a virtual alias map in `virtual.sympa` or a transport map in `transport.sympa`.  You shouldn't add such address to `sympa_transport` by editing it manually.

**Comment by qosobrin** [comment]
Thank you very much, @ikedas. After your clarification I close the issue.

Best regards.
