### ISSUE TITLE
Document external dependency to http://schemas.xmlsoap.org

### ISSUE THREAD

**Issue by dverdin** [sympa-community/sympa-community.github.io#97]
The new wsdl add reference to schema under the http://schemas.xmlsoap.org domain.

This should be documented to prevent the WSDL Sympa page to fail if the Sympa servers implements outgoing firewall filtering.

**Comment by ikedas** [comment]
The fact that schema validation can occur is an obvious requirement for SOAP. Also, since validation is not performed by the application server (SympaSOAP in our case), but by the client as needed, it is generally irrelevant whether the Sympa server is protected by such as firewall or not. Furthermore, whether or not the client performs schema validation is up to the client implementation and not a Sympa's requirement.
